### ISSUE TITLE
Synchronize beacon update listeners in beacon manager

### ISSUE THREAD

**Issue by marvinmirtschin** [neXenio/BLE-Indoor-Positioning#67]

**Comment by Steppschuh** [comment]
```
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at com.nexenio.bleindoorpositioning.ble.beacon.BeaconManager.notifyBeaconUpdateListeners(BeaconManager.java:100)
        at com.nexenio.bleindoorpositioning.ble.beacon.BeaconManager.processAdvertisingPacket(BeaconManager.java:78)
        at com.nexenio.bleindoorpositioning.ble.beacon.BeaconManager.processAdvertisingData(BeaconManager.java:54)
        at com.nexenio.authenticator.networking.bluetooth.NearbyDevicesManager.onScanResult(NearbyDevicesManager.java:218)
        at com.nexenio.authenticator.networking.bluetooth.NearbyDevicesManager.lambda$startScanning$2(NearbyDevicesManager.java:152)
        at com.nexenio.authenticator.networking.bluetooth.-$$Lambda$NearbyDevicesManager$3z2AY2Ysie8a5mXIbx0mQPopEkY.accept(Unknown Source:2)
```
