### ISSUE TITLE
TooManyEvaluationsException: illegal state: maximal count (1,000) exceeded: evaluations

### ISSUE THREAD

**Issue by Steppschuh** [neXenio/BLE-Indoor-Positioning#73]
```
2018-06-06 09:14:24.253 19160-19160/com.nexenio.bleindoorpositioning E/BluetoothClient: Bluetooth scanning error
    org.apache.commons.math3.exception.TooManyEvaluationsException: illegal state: maximal count (1,000) exceeded: evaluations
        at org.apache.commons.math3.optim.AbstractOptimizationProblem$MaxEvalCallback.trigger(AbstractOptimizationProblem.java:85)
        at org.apache.commons.math3.util.Incrementor.incrementCount(Incrementor.java:157)
        at org.apache.commons.math3.fitting.leastsquares.LevenbergMarquardtOptimizer.optimize(LevenbergMarquardtOptimizer.java:445)
        at com.lemmingapex.trilateration.NonLinearLeastSquaresSolver.solve(NonLinearLeastSquaresSolver.java:41)
        at com.lemmingapex.trilateration.NonLinearLeastSquaresSolver.solve(NonLinearLeastSquaresSolver.java:80)
        at com.lemmingapex.trilateration.NonLinearLeastSquaresSolver.solve(NonLinearLeastSquaresSolver.java:88)
        at com.nexenio.bleindoorpositioning.location.multilateration.Multilateration.findOptimum(Multilateration.java:65)
        at com.nexenio.bleindoorpositioning.location.multilateration.Multilateration.findOptimum(Multilateration.java:58)
        at com.nexenio.bleindoorpositioning.location.multilateration.Multilateration.getOptimum(Multilateration.java:123)
        at com.nexenio.bleindoorpositioning.location.multilateration.Multilateration.getLocation(Multilateration.java:109)
        at com.nexenio.bleindoorpositioning.IndoorPositioning.updateLocation(IndoorPositioning.java:93)
        at com.nexenio.bleindoorpositioning.IndoorPositioning.onBeaconUpdated(IndoorPositioning.java:73)
        at com.nexenio.bleindoorpositioning.ble.beacon.BeaconManager.notifyBeaconUpdateListeners(BeaconManager.java:102)
        at com.nexenio.bleindoorpositioning.ble.beacon.BeaconManager.processAdvertisingPacket(BeaconManager.java:79)
        at com.nexenio.bleindoorpositioning.ble.beacon.BeaconManager.processAdvertisingData(BeaconManager.java:55)
        at com.nexenio.bleindoorpositioningdemo.bluetooth.BluetoothClient.processScanResult(BluetoothClient.java:126)
        at com.nexenio.bleindoorpositioningdemo.bluetooth.BluetoothClient.access$100(BluetoothClient.java:28)
        at com.nexenio.bleindoorpositioningdemo.bluetooth.BluetoothClient$1.onNext(BluetoothClient.java:92)
        at com.nexenio.bleindoorpositioningdemo.bluetooth.BluetoothClient$1.onNext(BluetoothClient.java:79)
```

**Comment by marvinmirtschin** [comment]
The `org.apache.commons.math3.fitting.leastsquares.LevenbergMarquardtOptimizer` uses a `while (true)` loop in `optimize` for optimising our triliteration function. 
The `LevenbergMarquardtOptimizer` can be used more efficiently with the following parameters:

- initialStepBoundFactor: initial step bound factor

- costRelativeTolerance: cost relative tolerance

- parRelativeTolerance: parameters relative tolerance

- orthoTolerance: orthogonality tolerance

- qrRankingThreshold: threshold in the QR decomposition. Columns with a 2 norm less than this threshold are considered to be all 0s.
